apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nextjs-landing-dev
  namespace: dev
  labels:
    chart: nextjs-landing
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: nextjs-landing-dev
  chart:
    git: git@github.com:gyulavaripeter/gitops-pipeline
    path: charts/nextjs-landing
    ref: master
  values:
    image: 
      repository: gyulavaripeter/nextjs-landing
      tag: dev-88b25bd
    replicaCount: 1