apiVersion: v1
kind: Service
metadata:
  name: {{ include "quasar-chat.fullname" . }}
  labels:
{{ include "quasar-chat.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "quasar-chat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
