{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "quasar-chat.serviceAccountName" . }}
  labels:
{{ include "quasar-chat.labels" . | indent 4 }}
{{- end -}}
