apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nextjs-landing-rc
  namespace: stg
  labels:
    chart: nextjs-landing
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: nextjs-landing-rc
  chart:
    git: git@github.com:gyulavaripeter/gitops-pipeline
    path: charts/nextjs-landing
    ref: master
  values:
    image: 
      repository: gyulavaripeter/nextjs-landing
      tag: stg-6527b55
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50