apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: quasar-chat-stg
  namespace: stg
  labels:
    chart: quasar-chat
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: quasar-chat-stg
  chart:
    git: git@github.com:gyulavaripeter/gitops-pipeline
    path: charts/quasar-chat
    ref: master
  values:
    image: 
      repository: gyulavaripeter/quasar-chat
      tag: stg-dc01c34
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50