{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nextjs-landing.serviceAccountName" . }}
  labels:
{{ include "nextjs-landing.labels" . | indent 4 }}
{{- end -}}
